### YamlMime:Yaml
ms.openlocfilehash: e8e0c0487370439eb50ee376aa05769b8455f241
ms.sourcegitcommit: dc5e0864d5e723431a28f58082b91c4c4c796502
ms.translationtype: HT
ms.contentlocale: pt-BR
ms.lasthandoff: 01/12/2022
ms.locfileid: "135861518"
trigger:
- '*'
pool:
  vmImage: ubuntu-20.04
  demands:
  - npm #precisa-se do npm (gerenciador node.js) instalado no sistema de build
variables:
  buildConfiguration: Release
steps: #tarefas de build para cada um dos comandos de script
- task: UseDotNet@2 #é mapeada para ao utilitario da linha de comando dotnet
  displayName: Use .NET SDK 5.x
  inputs:
    packageType: sdk
    version: 5.x
- task: Npm@1
  displayName: Run npm install
  inputs:
    verbose: false #é tipo um @echooff
- script: ./node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot
  displayName: Compile Sass assets
- task: gulp@1
  displayName: Run gulp tasks
  #script executa comandos do sistema
- script: echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
  displayName: Write build info
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot
- task: DotNetCoreCLI@2 #restaurar dependendicas
  displayName: Restore project dependencies
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2 #criar o projeto
  displayName: Build the project - Release
  inputs:
    command: build
    arguments: --no-restore --configuration Release
    projects: '**/*.csproj'